sm8550-common: Patch IMS app | OS1.0.11.0 GL version
Issue:
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: org.codeaurora.ims, PID: 4180
E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/telephony/TelephonyBaseUtilsStub;
E AndroidRuntime: 	at org.codeaurora.ims.ImsServiceStateReceiver.updateHDIcon(ImsServiceStateReceiver.java:69)
E AndroidRuntime: 	at org.codeaurora.ims.ImsServiceSub.<init>(ImsServiceSub.java:326)
E AndroidRuntime: 	at org.codeaurora.ims.ImsSubController.createImsServiceSub(ImsSubController.java:245)
E AndroidRuntime: 	at org.codeaurora.ims.ImsSubController.<init>(ImsSubController.java:207)
E AndroidRuntime: 	at org.codeaurora.ims.ImsSubController.<init>(ImsSubController.java:198)
E AndroidRuntime: 	at org.codeaurora.ims.ImsService.setup(ImsService.java:42)
E AndroidRuntime: 	at org.codeaurora.ims.ImsService.onCreate(ImsService.java:72)
E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4912)
E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2407)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8595)
E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: android.telephony.TelephonyBaseUtilsStub
E AndroidRuntime: 	... 17 more

Solution:
Patched to remove com.qti.permission.BIND_QTI_IMS_SERVICE and
Landroid/telephony/TelephonyBaseUtilsStub;->isMiuiRom()

Patch:
https://paste.myself5.de/zitiketuto.diff

Co-authored-by: Arian <arian.kulmer@web.de>
Signed-off-by: Lunark :3 <jvillaltamatos3007@gmail.com>